//mocked data
export const MockPartFeaturesData = {

    "part_id":1,
    "part_name":"Part A",
    "features":[
        {
            "feature_id":1,
            "feature_name":"Seam",
            "status":"warning",
            "controls":[
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                }
            ]
        },
        {
            "feature_id":2,
           "feature_name":"Hole",
           "status":"bad",
           "controls":[
               {
                   "control_name":"X",
                   "dev":0,
                   "dev_tot":0,
                   "status":"ok"
               },
               {
                   "control_name":"Y",
                   "dev":0,
                   "dev_tot":0,
                   "status":"warning"
               },
               {
                   "control_name":"Z",
                   "dev":0,
                   "dev_tot":0,
                   "status":"bad"
               },
               {
                   "control_name":"Diameter",
                   "dev":0,
                   "dev_tot":0,
                   "status":"ok"
               },
               {
                   "control_name":"X",
                   "dev":0,
                   "dev_tot":0,
                   "status":"ok"
               },
               {
                   "control_name":"Y",
                   "dev":0,
                   "dev_tot":0,
                   "status":"warning"
               },
               {
                   "control_name":"Z",
                   "dev":0,
                   "dev_tot":0,
                   "status":"bad"
               },
               {
                   "control_name":"Diameter",
                   "dev":0,
                   "dev_tot":0,
                   "status":"ok"
               },
               {
                   "control_name":"X",
                   "dev":0,
                   "dev_tot":0,
                   "status":"ok"
               },
               {
                   "control_name":"Y",
                   "dev":0,
                   "dev_tot":0,
                   "status":"warning"
               },
               {
                   "control_name":"Z",
                   "dev":0,
                   "dev_tot":0,
                   "status":"bad"
               },
               {
                   "control_name":"Diameter",
                   "dev":0,
                   "dev_tot":0,
                   "status":"ok"
               }
           ]  
       },   
        {
            "feature_id":3,
            "feature_name":"Slot",
            "status":"ok",
            "controls":[
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                }
            ] 
        },
        {
            "feature_id":4,
            "feature_name":"Hole 2",
            "status":"warning",
            "controls":[
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                }
            ]  
        }
        
    ]
}

export const MockPartFeaturesData1 = {
    
        "part_id":1,
        "part_name":"Part 1",
        "features":[
            {
                "feature_id":1,
                "feature_name":"Seam",
                "status":"ok",
                "controls":[
                    {
                        "control_name":"X",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Y",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Z",
                        "dev":1,
                        "dev_tot":1,
                        "status":"ok"
                    },
                    {
                        "control_name":"Diameter",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"X",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Y",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Z",
                        "dev":1,
                        "dev_tot":1,
                        "status":"ok"
                    },
                    {
                        "control_name":"Diameter",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"X",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Y",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Z",
                        "dev":1,
                        "dev_tot":1,
                        "status":"ok"
                    },
                    {
                        "control_name":"Diameter",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"X",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Y",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Z",
                        "dev":1,
                        "dev_tot":1,
                        "status":"ok"
                    },
                    {
                        "control_name":"Diameter",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"X",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Y",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Z",
                        "dev":1,
                        "dev_tot":1,
                        "status":"ok"
                    },
                    {
                        "control_name":"Diameter",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"X",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Y",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Z",
                        "dev":1,
                        "dev_tot":1,
                        "status":"ok"
                    },
                    {
                        "control_name":"Diameter",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    }
                ]
            },
            {
                "feature_id":2,
               "feature_name":"Hole",
               "status":"ok",
               "controls":[
                   {
                       "control_name":"X",
                       "dev":1,
                       "dev_tot":1,
                       "status":"warning"
                   },
                   {
                       "control_name":"Y",
                       "dev":1,
                       "dev_tot":1,
                       "status":"warning"
                   },
                   {
                       "control_name":"Z",
                       "dev":1,
                       "dev_tot":1,
                       "status":"ok"
                   },
                   {
                       "control_name":"Diameter",
                       "dev":1,
                       "dev_tot":1,
                       "status":"warning"
                   },
                   {
                       "control_name":"X",
                       "dev":1,
                       "dev_tot":1,
                       "status":"warning"
                   },
                   {
                       "control_name":"Y",
                       "dev":1,
                       "dev_tot":1,
                       "status":"warning"
                   },
                   {
                       "control_name":"Z",
                       "dev":1,
                       "dev_tot":1,
                       "status":"ok"
                   },
                   {
                       "control_name":"Diameter",
                       "dev":1,
                       "dev_tot":1,
                       "status":"warning"
                   },
                   {
                       "control_name":"X",
                       "dev":1,
                       "dev_tot":1,
                       "status":"warning"
                   },
                   {
                       "control_name":"Y",
                       "dev":1,
                       "dev_tot":1,
                       "status":"warning"
                   },
                   {
                       "control_name":"Z",
                       "dev":1,
                       "dev_tot":1,
                       "status":"ok"
                   },
                   {
                       "control_name":"Diameter",
                       "dev":1,
                       "dev_tot":1,
                       "status":"warning"
                   }
               ]  
           },
            {
                "feature_id":3,
                "feature_name":"Slot",
                "status":"warning",
                "controls":[
                    {
                        "control_name":"X",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Y",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Z",
                        "dev":1,
                        "dev_tot":1,
                        "status":"ok"
                    },
                    {
                        "control_name":"Diameter",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    }
                ] 
            },
            {
                "feature_id":4,
                "feature_name":"Hole",
                "status":"bad",
                "controls":[
                    {
                        "control_name":"X",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Y",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    },
                    {
                        "control_name":"Z",
                        "dev":1,
                        "dev_tot":1,
                        "status":"ok"
                    },
                    {
                        "control_name":"Diameter",
                        "dev":1,
                        "dev_tot":1,
                        "status":"warning"
                    }
                ]  
            }
        ]
    }

    export const MockPartFeaturesData2 = {
        
            "part_id":1,
            "part_name":"Part 1",
            "features":[
                {
                    "feature_id":1,
                    "feature_name":"Seam",
                    "status":"warning",
                    "controls":[
                        {
                            "control_name":"X",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Y",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Z",
                            "dev":2,
                            "dev_tot":2,
                            "status":"ok"
                        },
                        {
                            "control_name":"Diameter",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"X",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Y",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Z",
                            "dev":2,
                            "dev_tot":2,
                            "status":"ok"
                        },
                        {
                            "control_name":"Diameter",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"X",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Y",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Z",
                            "dev":2,
                            "dev_tot":2,
                            "status":"ok"
                        },
                        {
                            "control_name":"Diameter",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"X",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Y",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Z",
                            "dev":2,
                            "dev_tot":2,
                            "status":"ok"
                        },
                        {
                            "control_name":"Diameter",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"X",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Y",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Z",
                            "dev":2,
                            "dev_tot":2,
                            "status":"ok"
                        },
                        {
                            "control_name":"Diameter",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"X",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Y",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Z",
                            "dev":2,
                            "dev_tot":2,
                            "status":"ok"
                        },
                        {
                            "control_name":"Diameter",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        }
                    ]
                },
                {
                    "feature_id":2,
                    "feature_name":"Hole",
                    "status":"ok",
                    "controls":[
                        {
                            "control_name":"X",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Y",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Z",
                            "dev":2,
                            "dev_tot":2,
                            "status":"ok"
                        },
                        {
                            "control_name":"Diameter",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"X",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Y",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Z",
                            "dev":2,
                            "dev_tot":2,
                            "status":"ok"
                        },
                        {
                            "control_name":"Diameter",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"X",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Y",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Z",
                            "dev":2,
                            "dev_tot":2,
                            "status":"ok"
                        },
                        {
                            "control_name":"Diameter",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        }
                    ]  
                },
                {
                    "feature_id":3,
                    "feature_name":"Slot",
                    "status":"warning",
                    "controls":[
                        {
                            "control_name":"X",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Y",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Z",
                            "dev":2,
                            "dev_tot":2,
                            "status":"ok"
                        },
                        {
                            "control_name":"Diameter",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        }
                    ] 
                },
                {
                    "feature_id":4,
                    "feature_name":"Hole 2",
                    "status":"bad",
                    "controls":[
                        {
                            "control_name":"X",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Y",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        },
                        {
                            "control_name":"Z",
                            "dev":2,
                            "dev_tot":2,
                            "status":"ok"
                        },
                        {
                            "control_name":"Diameter",
                            "dev":2,
                            "dev_tot":2,
                            "status":"bad"
                        }
                    ]  
                }   
            ]
        }


        export const MockPartFeaturesData3 = {
            
                "part_id":1,
                "part_name":"Part 1",
                "features":[
                    {
                        "feature_id":1,
                        "feature_name":"Seam",
                        "status":"warning",
                        "controls":[
                            {
                                "control_name":"X",
                                "dev":2,
                                "dev_tot":2,
                                "status":"ok"
                            },
                            {
                                "control_name":"Y",
                                "dev":2,
                                "dev_tot":4,
                                "status":"bad"
                            },
                            {
                                "control_name":"Z",
                                "dev":2,
                                "dev_tot":2,
                                "status":"ok"
                            },
                            {
                                "control_name":"Diameter",
                                "dev":2,
                                "dev_tot":2,
                                "status":"warning"
                            },
                            {
                                "control_name":"X",
                                "dev":2,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"Y",
                                "dev":5,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"Z",
                                "dev":2,
                                "dev_tot":2,
                                "status":"ok"
                            },
                            {
                                "control_name":"Diameter",
                                "dev":6,
                                "dev_tot":2,
                                "status":"warning"
                            },
                            {
                                "control_name":"X",
                                "dev":2,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"Y",
                                "dev":2,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"Z",
                                "dev":2,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"Diameter",
                                "dev":2,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"X",
                                "dev":2,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"Y",
                                "dev":5,
                                "dev_tot":6,
                                "status":"bad"
                            },
                            {
                                "control_name":"Z",
                                "dev":2,
                                "dev_tot":7,
                                "status":"ok"
                            },
                            {
                                "control_name":"Diameter",
                                "dev":7,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"X",
                                "dev":5,
                                "dev_tot":6,
                                "status":"bad"
                            },
                            {
                                "control_name":"Y",
                                "dev":2,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"Z",
                                "dev":2,
                                "dev_tot":2,
                                "status":"ok"
                            },
                            {
                                "control_name":"Diameter",
                                "dev":2,
                                "dev_tot":2,
                                "status":"ok"
                            },
                            {
                                "control_name":"X",
                                "dev":2,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"Y",
                                "dev":2,
                                "dev_tot":2,
                                "status":"warning"
                            },
                            {
                                "control_name":"Z",
                                "dev":2,
                                "dev_tot":2,
                                "status":"ok"
                            },
                            {
                                "control_name":"Diameter",
                                "dev":2,
                                "dev_tot":2,
                                "status":"bad"
                            }
                        ]
                    },
                    {
                        "feature_id":2,
                       "feature_name":"Hole",
                       "status":"warning",
                       "controls":[
                           {
                               "control_name":"X",
                               "dev":0,
                               "dev_tot":6,
                               "status":"bad"
                           },
                           {
                               "control_name":"Y",
                               "dev":2,
                               "dev_tot":6,
                               "status":"bad"
                           },
                           {
                               "control_name":"Z",
                               "dev":2,
                               "dev_tot":6,
                               "status":"bad"
                           },
                           {
                               "control_name":"Diameter",
                               "dev":2,
                               "dev_tot":2,
                               "status":"warning"
                           },
                           {
                               "control_name":"X",
                               "dev":2,
                               "dev_tot":6,
                               "status":"warning"
                           },
                           {
                               "control_name":"Y",
                               "dev":2,
                               "dev_tot":4,
                               "status":"bad"
                           },
                           {
                               "control_name":"Z",
                               "dev":0,
                               "dev_tot":2,
                               "status":"ok"
                           },
                           {
                               "control_name":"Diameter",
                               "dev":2,
                               "dev_tot":2,
                               "status":"warning"
                           },
                           {
                               "control_name":"X",
                               "dev":2,
                               "dev_tot":2,
                               "status":"bad"
                           },
                           {
                               "control_name":"Y",
                               "dev":3,
                               "dev_tot":5,
                               "status":"ok"
                           },
                           {
                               "control_name":"Z",
                               "dev":2,
                               "dev_tot":2,
                               "status":"ok"
                           },
                           {
                               "control_name":"Diameter",
                               "dev":0,
                               "dev_tot":0,
                               "status":"ok"
                           }
                       ]  
                   },
                    {
                        "feature_id":3,
                        "feature_name":"Slot",
                        "status":"bad",
                        "controls":[
                            {
                                "control_name":"X",
                                "dev":5,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"Y",
                                "dev":2,
                                "dev_tot":6,
                                "status":"bad"
                            },
                            {
                                "control_name":"Z",
                                "dev":2,
                                "dev_tot":2,
                                "status":"warning"
                            },
                            {
                                "control_name":"Diameter",
                                "dev":2,
                                "dev_tot":2,
                                "status":"bad"
                            }
                        ] 
                    },
                    {
                        "feature_id":4,
                        "feature_name":"Hole 2",
                        "status":"ok",
                        "controls":[
                            {
                                "control_name":"X",
                                "dev":6,
                                "dev_tot":2,
                                "status":"bad"
                            },
                            {
                                "control_name":"Y",
                                "dev":2,
                                "dev_tot":4,
                                "status":"warning"
                            },
                            {
                                "control_name":"Z",
                                "dev":2,
                                "dev_tot":2,
                                "status":"ok"
                            },
                            {
                                "control_name":"Diameter",
                                "dev":3,
                                "dev_tot":1,
                                "status":"ok"
                            }
                        ]  
                    }  
                ]
            }