//mocked data
export const MockPartFeaturesData = {

    "part_id":1,
    "part_name":"Part 1",
    "features":[
        {
            "feature_id":1,
            "feature_name":"Seam",
            "status":"warning",
            "controls":[
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                }
            ]
        },
        {
            "feature_id":2,
            "feature_name":"Slot",
            "status":"ok",
            "controls":[
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                }
            ] 
        },
        {
            "feature_id":3,
            "feature_name":"Hole",
            "status":"warning",
            "controls":[
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                }
            ]  
        },
        {
            "feature_id":4,
            "feature_name":"Slot 2",
            "status":"bad",
            "controls":[
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                }
            ]  
        },
        {
            "feature_id":5,
            "feature_name":"Seam 2",
            "status":"ok",
            "controls":[
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                }
            ]  
        },
        {
             "feature_id":6,
            "feature_name":"Hole 2",
            "status":"bad",
            "controls":[
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"X",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                },
                {
                    "control_name":"Y",
                    "dev":0,
                    "dev_tot":0,
                    "status":"warning"
                },
                {
                    "control_name":"Z",
                    "dev":0,
                    "dev_tot":0,
                    "status":"bad"
                },
                {
                    "control_name":"Diameter",
                    "dev":0,
                    "dev_tot":0,
                    "status":"ok"
                }
            ]  
        }   
    ]
}